name: vHive KinD 2

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

defaults:
  run:
    shell: bash

jobs:
  vhive-kind-2:
    name: vHive KinD 2
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      
      - name: Install KinD
        run: |
          set -x

          curl -sL get.konk.dev | bash
          
      - name: Up chained-function-eventing
        run: |
          set -x

          ./function-images/tests/chained-function-eventing/manifests/apply.sh
      
      - name: Invoke
        run: |
          set -x

          ./bin/grpcurl -d '{\"name\": \"Bora\"}' -plaintext $(kubectl -n chained-functions-eventing get ksvc producer -o jsonpath='{.status.url}'):80 helloworld.Greeter.SayHello
